spring:
  r2dbc:
    host: localhost
    port: 5432
    db: word_lift
    url: r2dbc:postgresql://localhost:5432/word_lift
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/word_lift
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/changelog.sql

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG